### ISSUE TITLE
Difficulty modifying CSV file

### ISSUE THREAD

**Issue by mavedisian** [googlemaps/js-store-locator#5]
Hello - thanks for the great script! 

I'm using the static-based example, and I've got everything working correctly, however I can't seem to modify the csv file. I can use the example one fine -  but as soon as I export it in any capacity (changed or unchanged), it stops displaying locations. I've tried saving out of excel in multiple csv formats (normal, microsoft based, ms-dos based), and they all stop functioning. 

I couldn't find anything in the docs concerning the csv file. Are there any guidelines for modifying the csv file as far as formats, best practices, required headers, etc?

**Comment by broady** [comment]
It's not an actual CSV parser. CSV is actually rather complex and that script is only designed to parse the example CSV file.

**Comment by barryvdh** [comment]
Shouldn't we replace the example/parser with a something real? Like a json file?
This might give people the wrong impression and try to use the csv parser in production..

**Comment by jenjika** [comment]
Same problem

**Comment by Emma-Dolan** [comment]
Just spent hours trying to modify the csv file. Even if I only change one letter in the csv or change the filename itself it doesn't show. As you say it's designed for the example csv, could you please provide an example json file and modified code to show that instead? Thanks

**Comment by bilgert** [comment]
Same problem, hoping for an update.

**Comment by hfjansen** [comment]
Is there a solution for this problem? Same problem here

**Comment by Tfx77** [comment]
You can, you just need to get the format correct. You are better off editing it in a text document. Basically, the issue is that the csv has all data encapsulated in quotation marks and delimited by commas. If you edit this in excel then excel will just use the comma as a delimiter and strip the extra quotation marks and this breaks the built in parser. Try it, open the excel that comes with the repository in a text editor like notepad and then save the file through excel and you will see the tags stripped. Worked for me anyway and I have been able to use my own data in the csv file.

**Comment by hfjansen** [comment]
Thanks for the reply. I will try it.
M.vr.gr.
Erik Jansen

Verstuurd vanaf mijn iPad

**Comment by barryvdh** [comment]
You shouldn't process csv files with javascript. Just parse them server side to json or something.

**Comment by hfjansen** [comment]
It worked for me with JS.

M.vr.gr.
Erik

Verstuurd vanaf mijn iPad

**Comment by MelR** [comment]
As noted by @Tfx77 editing the CSV directly in a text editor works. But it would be so nice if this worked with a comma separated list rather than double quoted comma separated list so a spreadsheet program like Google Sheets or Excel could be used to edit the CSV file.

**Comment by MelR** [comment]
After some digging I found this can be done. In static-ds.js I changed:

`MedicareDataSource.prototype.parseRow_ = function(row) {
  // Strip leading quote.
  if (row.charAt(0) == '"') {
    row = row.substring(1);
  }
  // Strip trailing quote. There seems to be a character between the last quote
  // and the line ending, hence 2 instead of 1.
  if (row.charAt(row.length - 2) == '"') {
    row = row.substring(0, row.length - 2);
  }

  row = row.split('","');

  return row;
};`

To:

`MedicareDataSource.prototype.parseRow_ = function(row) {
  row = row.split(',');
  return row;
};`

**Comment by domesticmouse** [comment]
This project is in an unmaintained state. I suggest you look at our [Google Maps APIs Solutions](https://developers.google.com/maps/solutions/) for currently maintained store locator solutions.
